### ISSUE TITLE
Težave z NA

### ISSUE THREAD

**Issue by tajadebeljak** [tajadebeljak/APPR-2015-16#2]
Med podatki s katerimi računam imajo nekateri vrednost NA. Zato mi, ko jih naprimer seštejem, na koncu vrne NA, pri nekaterih pa kar 0.00. Zanima me kako naj to popravim.

**Comment by jaanos** [comment]
Funkciji `sum` dodaj parameter `na.rm = TRUE`, da ti `NA`-je ignorira.

Sicer pa lahko vsote po starostih lažje izračunaš s pomočjo funkcij `group_by` in `summarize`:

``` R
prenocitve_slo_tujina <- filter(potovanja,
                                `Povprecno.stevilo.nocitev.in.izdatkov`=="Povprečno število prenočitev") %>%
  group_by(Starost, Destinacija) %>% summarize(sum(Meritve, na.rm = TRUE)) %>% data.frame()
```
