### ISSUE TITLE
filter in poročilo

### ISSUE THREAD

**Issue by tajadebeljak** [tajadebeljak/APPR-2015-16#3]
Pri obdelavi HTML podatkov želim ustvariti dva vektorja: izdatki_zasebno in izdatki_poslovno, pri obeh mi javlja napako glede funkcije filter, pa ne vem zakaj. 
Poleg tega ne vem tudi zakaj mi ne prevede poročila

**Comment by tajadebeljak** [comment]
pri poročilu mi napiše tole:
processing file: projekt.Rmd
Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label 'razpredelnice'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted

**Comment by jaanos** [comment]
Pri `filter` delaš prmerjave - uporabiti moraš dvojne enačaje.

Sicer pa bo lažje narediti to:

``` R
izdatki_zasebno <- tabela2 %>% filter(Vrsta_potovanja == "Zasebna potovanja",
                                      Izdatki %in% c("Izdatki za nastanitev",
                                                     "Izdatki za prevoz")) %>%
  group_by(Destinacija, Izdatki) %>% summarize(sum(Meritve, na.rm = TRUE))
```

Iz dobljene razpredelnice potem lahko potegneš zadnji stolpec.

Pri poročilu pride do napake, ker imaš dva bloka kode z oznako `razpredelnice`. Ni potrebno, da ima vsak blok svojo oznako, obstoječe pa morajo biti različne. Meni potem sicer ne prevede v PDF (nisem prepričan, zakaj), deluje pa prevajanje v HTML.

Da ti ne bo izpisovalo sporočil ob uvozu knjižnic v poročilo, premakni še ukaze `library` iz `uvoz.r` v `lib/libraries.r`.

**Comment by tajadebeljak** [comment]
Hvala! Poročilo mi zdaj deluje
