### ISSUE TITLE
zemljevid

### ISSUE THREAD

**Issue by tajadebeljak** [tajadebeljak/APPR-2015-16#4]
zanima me zakaj mi pri uvozu zemljevida, pri uporabi funkcije preuredi vedno ko napišem: 
destinacije2 <- preuredi(tabela4, zemljevid, sovereignt)

javlja napako:  Error in zemljevid[[stolpec]] : 
  error in evaluating the argument 'i' in selecting a method for function '[[': Error: object 'sovereignt' not found

'sovereignt' je ime stolpca v tabeli 'zemljevid'

**Comment by jaanos** [comment]
Pri `preuredi` je potrebno ime stolpca podati kot niz, torej v navednicah.

Glede na to, da se ti imena držav iz `tabela4` popolnoma ujemajo s tistimi v zemljevidu, bo bolje, če namesto `preuredi` (ki očitno tukaj ne deluje pravilno) uporabiš `match`, da dobiš vrstni red vrstic iz tabele, ki ustreza zemljevidu:

``` R
m <- match(zemljevid$name, tabela4$Drzava)
zemljevid$Prihodi2014 <- tabela4$Prihodi2014[m] # stolpec Prihodi2014 kopiramo v zemljevid
```

Še to: da ti bo pravilno prebralo vsa imena držav, pri uvozu zemljevida uporabi kodiranje `"Windows-1252"`.

**Comment by tajadebeljak** [comment]
hvala!

**Comment by tajadebeljak** [comment]
Tam, kjer ste v funkciji match napisali 'name' je mišljeno ime stolpca v tabeli 'zemljevid', ki se mora ujemati s stolpcem 'Drzava' v 'tabela4'?

**Comment by jaanos** [comment]
Tako je - pravzaprev je `name` že takšen stolpec (ki je v bistvu nekoliko bolj natančen kot `sovereignt`, saj loči tudi ozemlja, ki niso neodvisne države).

**Comment by tajadebeljak** [comment]
Hvala, tega stolpca sploh nisem opazila.
Sedaj sem naredila vse kot se mi zdi da bi moglo biti pa mi še vedno noče izrisati zemljevida

**Comment by jaanos** [comment]
Znotraj `aes` podajaj samo imena stolpcev razpredelnice, podane pri `data`. V tvojem primeru torej uporabi `fill = Prihodi2014`.

**Comment by tajadebeljak** [comment]
super, hvala, to mi sedaj dela. Nevem pa zakaj mi noče prevesti poročila?

**Comment by jaanos** [comment]
V poročilu imaš sedaj tri kode bloke z oznako `graf`. Oznake niso obvezne (so pa koristne predvsem za sklicevanje na slike), obstoječe oznake pa morajo biti vse različne. Svetujem torej, da uporabiš oznake `graf1`, `graf2`, `graf3` (ali pa kaj bolj informativnega - pazi le, da ne uporabljaš presledkov in šumnikov).

**Comment by tajadebeljak** [comment]
Najlepša hvala!

**Comment by jaanos** [comment]
Poročila ti sedaj ne prevede, saj nikjer ne kličeš programa `vizualizacija/vizualizacija.r`, potem pa se sklicuješ na spremenljivko `zem`, ki je tam definirana. Vključi torej ta program (podobno kot `libraries.r` in `uvoz.r` - lahko kar takoj za slednjim), v `vizualizacija.r` pa odstrani vrstico `print(zem)`, da se zemljevid ne bo dvakrat izrisal. Bloku kode, kjer boš vključila `vizualizacija.r`, dodaj tudi parameter `message = FALSE`, da se v poročilo ne bodo izpisovala obvestila.

**Comment by tajadebeljak** [comment]
Super, hvala, sem uredila in mi ga prevede

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo.
