### ISSUE TITLE
fmf

### ISSUE THREAD

**Issue by tajadebeljak** [tajadebeljak/APPR-2015-16#5]
pozdravljeni, 
zanima me zakaj mi ne dela funkcija: graf_potovanj <- graf_potovanj + geom_smooth(method = "lm", formula =y ~ x)
Izriše mi namreč graf s pikicami, ne nariše pa premice skozi nijh.

**Comment by jaanos** [comment]
Problem je ta, da imaš na osi x nize. Četrtletja bo torej treba pretvoriti v števila, da lahko delaš modele z njimi.

**Comment by tajadebeljak** [comment]
sedaj sem hotela za vsako četrtletje posebaj spremeniti v števila s funkcijo: potovanja2$Četrtletje <- gsub("Q1", ".00", potovanja2$Četrtletje) %>% as.numeric(), 
a mi pretvori le za 1 četrtletje, pri vseh ostalih pa v tabeli izpiše NA

**Comment by tajadebeljak** [comment]
javi pa tole napako:
Warning message:
In function_list[[k]](value) : NAs introduced by coercion

**Comment by jaanos** [comment]
Problem je v tem, da si zamenjavo naredila samo za eno četrtletje, ostalih pa ni uspelo pretvoriti v števila. Pretvorbo lahko narediš tako:

``` R
potovanja2$Četrtletje <- potovanja2$Četrtletje %>%
  strapplyc("([0-9]+)Q([0-9])") %>% lapply(as.numeric) %>%
  sapply(. %>% {.[[1]] + (.[[2]]-1)/4})
```

Najprej torej pobereš številke, jih pretvoriš v števila, potem pa združiš.

**Comment by tajadebeljak** [comment]
super, najlepša hvala
